### ISSUE TITLE
Salut à toi

### ISSUE THREAD

**Issue by GiJoe83** [medaion/Ereborosa#1]
https://github.com/PC-Gamercom/pcg_tanoa/issues/2

Je t'ai mis une petite question sur le post tanoa pcg,
Quand tu as le temps de me poster une petite réponse,
Mon steam c'est GiJoe_83 si besoin,
Merci à toi,

https://github.com/PC-Gamercom/pcg_tanoa/issues/2

**Comment by medaion** [comment]
Bonsoir , je viens de te répondre sur le poste ;) 
J'ai vue quand je suis allez sur mon hotmail que tu m'avais écrie . 

Si tu as d'autre questions hésite pas je répondrais des que possible . 
Je viens une fois par 2 jour voir les discutions ect ... 

Si tu trouve comment intégré le shop 3D , fais moi signe ou comment réglé l'assurance !
J'ai beau cherche pour le moment je trouve pas comment les installé XD

Si j'amais tu y arrive pas du tout dans 1 ou 2 semaine je sort une versions de tanoa stable .
Avec ce core mes avec mes modifications & tout mes fixe !
